name: 'Rebol-Triangulate CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 64bit Rebol Triangulate extension
      run: ./siskin Rebol-Triangulate.nest --msvc -o ./triangulate-windows-x64.rebx %triangulate-x64

    - name: Build 32bit Rebol Triangulate extension
      run: ./siskin Rebol-Triangulate.nest --msvc -o ./triangulate-windows-x86.rebx %triangulate-x86

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.17.0
      with:
        product: Bulk

    - name: Test Triangulate extension
      run:  ./rebol3 ci-test.r3


    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-Triangulate-CI-${{github.run_id}}
        path: ./triangulate-windows-*.rebx

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.17.0

#      - name: Build 32bit Rebol Triangulate extension
#        run: ./siskin Rebol-Triangulate.nest [%triangulate-linux-x86]

      - name: Build 64bit Rebol Triangulate extension
        run: ./siskin Rebol-Triangulate.nest %triangulate-x64

#      - name: Prepare 32bit Rebol Triangulate extension
#        run:  |
#          mv .\build\triangulate-linux-x86.so triangulate-linux-x86.rebx
#          gzip -9 ./triangulate-linux-x86.rebx

      - name: Prepare 64bit Rebol Triangulate extension
        run:  mv ./build/triangulate-x64.so triangulate-linux-x64.rebx

      - name: Install Rebol for extension test
        uses: oldes/install-rebol@v3.17.0
        with:
          product: Bulk

      - name: Test Triangulate extension
        run:  ./rebol3 ci-test.r3

      - name: Compress 64bit Rebol Triangulate extension
        run:  gzip -9 ./triangulate-linux-x64.rebx

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Triangulate-CI-${{github.run_id}}
          path: ./triangulate-linux-*

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.17.0

      - name: Build x64 Rebol Triangulate extension
        run: ./siskin Rebol-Triangulate.nest -o ./triangulate-macos-x64.rebx %triangulate-x64

      - name: Build arm64 Rebol Triangulate extension
        run: ./siskin Rebol-Triangulate.nest -o ./triangulate-macos-arm64.rebx %triangulate-arm64

      - name: Install Rebol for extension test
        uses: oldes/install-rebol@v3.17.0
        with:
          product: Bulk

      - name: Test Triangulate extension
        run:  ./rebol3 ./ci-test.r3

      - name: Compress x64 Rebol Triangulate extension
        run:  gzip -9 ./triangulate-macos-x64.rebx

      - name: Compress arm64 Rebol Triangulate extension
        run:  gzip -9 ./triangulate-macos-arm64.rebx

      - uses: actions/upload-artifact@v3
        with:
          name: Rebol-Triangulate-CI-${{github.run_id}}
          path: ./triangulate-macos-*